sonar.projectKey=digital-wallet-system
sonar.projectName=Digital Wallet System
sonar.sourceEncoding=UTF-8
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=auth-service/target/site/jacoco/jacoco.xml,user-service/target/site/jacoco/jacoco.xml,wallet-service/target/site/jacoco/jacoco.xml,transaction-service/target/site/jacoco/jacoco.xml,rewards-service/target/site/jacoco/jacoco.xml,notification-service/target/site/jacoco/jacoco.xml,admin-service/target/site/jacoco/jacoco.xml
sonar.exclusions=**/target/**,**/.m2/**,**/.metadata/**,**/.sonarlint/**
